# Generated by Django 5.2 on 2025-05-02 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Savol')),
                ('answer', models.TextField(verbose_name='Javob')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'FAQ Savol-Javob',
                'verbose_name_plural': 'FAQ Savol-Javoblar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Stipendiya nomi')),
                ('provider', models.CharField(max_length=255, verbose_name="Ta'minotchi")),
                ('description', models.TextField(verbose_name='Tavsif va Talablar')),
                ('amount', models.CharField(max_length=100, verbose_name='Miqdori/Qoplash')),
                ('deadline', models.DateField(verbose_name='Topshirish muddati')),
                ('field', models.CharField(choices=[('all', 'Barcha mutaxassisliklar'), ('technical_natural', 'Texnik, Tabiiy fanlar'), ('humanities_art', "Gumanitar fanlar, San'at"), ('social', 'Ijtimoiy ahamiyatga ega'), ('science_culture_art', "Fan, Madaniyat, San'at"), ('it', 'Axborot texnologiyalari'), ('agriculture', "Qishloq xo'jaligi"), ('engineering_geology', 'Muhandislik, Geologiya')], max_length=100, verbose_name='Soha/Mutaxassisliklar')),
                ('type', models.CharField(choices=[('international', 'Xalqaro'), ('state', 'Davlat'), ('private', 'Xususiy'), ('regional', 'Mintaqaviy'), ('corporate', 'Korporativ')], max_length=20, verbose_name='Stipendiya turi')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('completed', 'Tugallangan'), ('draft', 'Qoralama')], default='draft', max_length=15, verbose_name='Holati')),
                ('popular', models.BooleanField(default=False, verbose_name='Ommabop')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Stipendiya',
                'verbose_name_plural': 'Stipendiyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan sana')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilanish')),
                ('status', models.CharField(choices=[('submitted', 'Yuborilgan'), ('reviewing', "Ko'rib chiqilmoqda"), ('clarification', 'Aniqlashtirish talab etiladi'), ('approved', "Ma'qullangan"), ('rejected', 'Rad etilgan'), ('withdrawn', 'Qaytarib olingan')], default='submitted', max_length=20, verbose_name='Holati')),
                ('review_notes', models.TextField(blank=True, null=True, verbose_name="Ko'rib chiquvchi izohlari")),
                ('applicant_full_name', models.CharField(max_length=255, verbose_name='Ariza beruvchi F.I.Sh.')),
                ('applicant_birth_date', models.DateField(verbose_name="Ariza beruvchi tug'ilgan sana")),
                ('applicant_iin', models.CharField(max_length=14, verbose_name='Ariza beruvchi JShShIR')),
                ('applicant_phone', models.CharField(max_length=20, verbose_name='Ariza beruvchi telefoni')),
                ('applicant_email', models.EmailField(max_length=254, verbose_name='Ariza beruvchi email')),
                ('applicant_address', models.TextField(verbose_name='Ariza beruvchi manzili')),
                ('university', models.CharField(max_length=255, verbose_name="Ta'lim muassasasi")),
                ('faculty', models.CharField(max_length=255, verbose_name='Fakultet/Mutaxassislik')),
                ('course', models.PositiveSmallIntegerField(verbose_name="Kurs/O'quv yili")),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name="O'rtacha baho (GPA)")),
                ('achievements', models.TextField(blank=True, null=True, verbose_name='Yutuqlar va Tajriba')),
                ('essay', models.TextField(blank=True, null=True, verbose_name='Esse')),
                ('confirm_accuracy', models.BooleanField(default=False, verbose_name="To'g'rilik tasdiqlangan")),
                ('confirm_terms', models.BooleanField(default=False, verbose_name='Shartlarga rozilik bildirilgan')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Ariza beruvchi')),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='appx.scholarship', verbose_name='Stipendiya')),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_card', 'Shaxsni tasdiqlovchi hujjat/Pasport'), ('transcript', 'Baho daftarchasi/Attestat'), ('motivation', 'Motivatsion xat'), ('recommendation', 'Tavsiyanoma'), ('other', 'Boshqa')], max_length=20, verbose_name='Hujjat turi')),
                ('file', models.FileField(upload_to='application_documents/', verbose_name='Fayl')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan sana')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='appx.application', verbose_name='Ariza')),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Havola')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('applicant', 'Ariza beruvchi'), ('reviewer', 'Tekshiruvchi'), ('admin', 'Administrator'), ('superadmin', 'Super Admin')], default='applicant', max_length=20, verbose_name='Rol')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('iin', models.CharField(blank=True, max_length=14, null=True, verbose_name='JShShIR')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Yashash manzili')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profillar',
            },
        ),
    ]
